### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by AnasMAC** [nedlir/languagepod101-scraper#27]
icrosoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ert>"C:/Program Files/Python312/python.exe" c:/Users/ert/Downloads/languagepod101-scraper-2023update/languagepod101-scraper-2023update/language101_scraper.py
Traceback (most recent call last):
  File "c:\Users\ert\Downloads\languagepod101-scraper-2023update\languagepod101-scraper-2023update\language101_scraper.py", line 10, in <module>
    import requests
  File "C:\Users\ert\AppData\Roaming\Python\Python312\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by nedlir** [comment]
Should work now with latest commit.
